import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import Nav from '@/app/ui/nav';
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Nav />
        <main className="flex mx-auto min-h-screen flex-col p-6 w-full md:max-w-[1000px]">
          {children}
        </main>
      </body>
    </html>
  );
}
